name: Deploy to Server

on:
  push:
    branches:
      - master  # Триггер на пуш в ветку main
  pull_request:
    branches: [ "master" ]


jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -f tests/Dockerfile -t tests .
      - name: Run Tests in Container
        run: docker run --rm tests

  publish-to-pypi:
    name: Publish to PyPI
    needs: [tests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      poetry_version: 1.8.5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          pip install poetry==$poetry_version
      - name: Set up the pypi token
        run: |
          poetry config pypi-token.pypi  ${{ secrets.PYPI_TOKEN }} && \
          poetry publish --build 



